name: spicehut_admin_panel
description: Admin Panel for Spice Hut Restaurant
publish_to: 'none'
version: 3.3.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.0
  audioplayers: ^6.1.0
  shared_preferences: ^2.2.0
  http: ^1.1.0
  intl: ^0.19.0
  image_picker: ^1.0.0
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.2.6
  pdf: ^3.10.8
  printing: ^5.13.0
  permission_handler: ^11.4.0
  flutter_esc_pos_utils: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/spicehut_logo.png
    - assets/sounds/ringtone.mp3

flutter_launcher_icons:
  image_path: "assets/logo/spicehut_logo.png"
  android:
    notification_icon: "ic_launcher"
  ios: true
  remove_alpha_ios: true
